{
  .tag     = "CM0",
  .name    = "Cortex-M0",
  .rev     = "CM0",
  .include = "core_cm0.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = NULL,
     [5] = NULL,
     [6] = NULL,
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = NULL,
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM0PLUS",
  .name    = "Cortex-M0+",
  .rev     = "CM0PLUS",
  .include = "core_cm0plus.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = NULL,
     [5] = NULL,
     [6] = NULL,
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = NULL,
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM0+",
  .name    = "Cortex-M0+",
  .rev     = "CM0PLUS",
  .include = "core_cm0plus.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = NULL,
     [5] = NULL,
     [6] = NULL,
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = NULL,
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM1",
  .name    = "Cortex-M1",
  .rev     = "CM1",
  .include = "core_cm1.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = NULL,
     [5] = NULL,
     [6] = NULL,
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = NULL,
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM3",
  .name    = "Cortex-M3",
  .rev     = "CM3",
  .include = "core_cm3.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = "MemoryManagement",
     [5] = "BusFault",
     [6] = "UsageFault",
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = "DebugMonitor",
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM4",
  .name    = "Cortex-M4",
  .rev     = "CM4",
  .include = "core_cm4.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = "MemoryManagement",
     [5] = "BusFault",
     [6] = "UsageFault",
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = "DebugMonitor",
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM7",
  .name    = "Cortex-M7",
  .rev     = "CM7",
  .include = "core_cm7.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = "MemoryManagement",
     [5] = "BusFault",
     [6] = "UsageFault",
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = "DebugMonitor",
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM23",
  .name    = "Cortex-M23",
  .rev     = "CM23",
  .include = "core_cm23.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = NULL,
     [5] = NULL,
     [6] = NULL,
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = NULL,
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM33",
  .name    = "Cortex-M33",
  .rev     = "CM33",
  .include = "core_cm33.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = "MemoryManagement",
     [5] = "BusFault",
     [6] = "UsageFault",
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = "DebugMonitor",
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},
{
  .tag     = "CM35P",
  .name    = "Cortex-M35P",
  .rev     = "CM35",
  .include = "core_cm35p.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = "MemoryManagement",
     [5] = "BusFault",
     [6] = "UsageFault",
     [7] = NULL,
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = "DebugMonitor",
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},

{
  .tag     = "CM55",
  .name    = "Cortex-M55",
  .rev     = "CM55",
  .include = "core_cm55.h",
  .vectors =
  {
     [0] = NULL,
     [1] = "Reset",
     [2] = "NonMaskableInt",
     [3] = "HardFault",
     [4] = "MemoryManagement",
     [5] = "BusFault",
     [6] = "UsageFault",
     [7] = "SecureFault",
     [8] = NULL,
     [9] = NULL,
    [10] = NULL,
    [11] = "SVCall",
    [12] = "DebugMonitor",
    [13] = NULL,
    [14] = "PendSV",
    [15] = "SysTick",
  },
},

